### PR TITLE
Turn these policies into a new Contributing Guide

### PR DESCRIPTION
**Pull request by moeenio**
This is an attempt to turn the policies into an insightful, welcoming and friendly Contributing Guide. Please tell me what do you think of it, what I missed, what should I add, improve or remove, or if I should fire and give up on the whole thing 😀 

To-do
- [x] Maybe add some guides about the Git and GitHub workflow

Backlog To-do
- [x] Rename the repository
- [ ] Make a uniform README template
- [ ] Apply it to repositories
	- [ ] Client
	- [ ] Mobile
	- [ ] Landing

cc @Scratch-Client-4/everyone

### CODE REVIEW

**Review by micahlt — COMMENTED** [review]
Looking good!  Merge when you're ready.

**Comment by locness3** [comment]
I've added some learning resources. Also, when this is merged, we should :

- [ ] Rename this repository
- [ ] Make a uniform README template for all projects

**Comment by moeenio** [comment]
I'm waiting for more people's approval :)

Also, I added a "Backlog To-do" to the first comment.

**Comment by githubfan** [comment]
Looks alright to me!

**Review by githubfan — APPROVED** [review]
Looking good!

**Comment by moeenio** [comment]
Well, I guess I'll merge.

**Pull request merged**
